export class StationRankingResp {
  content: [
    {
      stationId: string,
      stationName: string,
      shortName: string,
      timezone: string,
      address: string,
      postcode: string,
      longitude: string,
      latitude: string,
      countryId: string,
      countryName: string,
      provinceId: string,
      provinceName: string,
      cityId: string,
      cityName: string,
      countyId: string,
      countyName: string,
      designComp: string,
      designCompName: string,
      construnctComp: string,
      construnctCompName: string,
      powerComp: string,
      powerCompName: string,
      projectComp: string,
      projectCompName: string,
      propertyComp: string,
      propertyCompName: string,
      customerId: string,
      customerName: string,
      deptId: string,
      deptName: string,
      parentDeptId: string,
      parentDeptName: string,
      area: string,
      capacity: number,
      connectionMode: string,
      connectionModeText: string,
      voltageLevel: string,
      voltageLevelText: string,
      elevation: string,
      elevationText: string,
      finishDate: string,
      operationDate: string,
      introduction: string, psrId: string,
      stationMaster: string,
      stationMasterName: string,
      stationStatus: string,
      stationStatusText: string,
      stationType: string,
      stationTypeText: string,
      modelLayout: string,
      modelLayoutText: string,
      modelAngle: string,
      modelAngleText: string,
      collStationId: string,
      attributes: string,
      areas: string,
      points: [
        {
          pointId: number,
          importBatchNo: number,
          isDisplay: string,
          objId: string,
          objType: string,
          calcFormula: string,
          pointName: string,
          cateId: string,
          calcPeriod: string,
          dataPeriod: string,
          pointCategory: {
            cateId: string,
            calcPeriod: string,
            cateName: string,
            dataPeriod: string,
            dataType: string,
            displayGroup1: string,
            displayGroup2: string,
            displayOrder1: number,
            displayOrder2: number,
            displayOrder3: number,
            displayPrecision: number,
            importBatchNo: number,
            persistenceType: string,
            pointClass: string,
            pointUnit: string,
            propTypeId: string,
            remotionType: string,
            sysCateId: string,
            isDisplay: string,
            nullable: string,
          },
          currValue: {
            _id: number,
            pid: number,
            v: number,
            dt: number,
            t: number,
            q: number,
            oldValue: number
          },
          historyValues: number
        }
      ]
    }
  ];
  last: boolean;
  totalElements: number;
  totalPages: number;
  size: number;
  sort: string;
  first: boolean;
  numberOfElements: number;
}
